// Copyright (c) 2026 bentzn
// SPDX-License-Identifier: Apache-2.0
package com.raposza.canton.topology;

import com.raposza.canton.install.HostPlatform;
import com.raposza.canton.jdbc.PgShim;

/**
 * The two ledger-side datasources that ask PostgreSQL for a check it cannot
 * perform on Windows, and the only two that a configuration can reach.
 *
 * <h2>Three senders, two mechanisms</h2>
 *
 * `client_connection_check_interval` polls the socket for a close event and
 * PostgreSQL implements it only where the kernel exposes that, so on Windows
 * the postmaster refuses every nonzero value. Canton sends 5s from three
 * places, and they do NOT share a fix:
 *
 * <ul>
 * <li>Every node's migration lock, from a constructor default. It goes through
 *     the storage block's DataSource, and NO configuration path reaches the
 *     value - {@link PgShim} answers that one in the DataSource itself.</li>
 * <li>The ledger API's own datasource, at `ledger-api.postgres-data-source`.
 *     This one IS configuration.</li>
 * <li>The indexer's separate copy, at
 *     `parameters.ledger-api-server.indexer.postgres-data-source`. Also
 *     configuration, and a different object from the one above - silencing
 *     either alone leaves the other refusing.</li>
 * </ul>
 *
 * The last two are what this class writes. They cannot be answered by the
 * DataSource class: both are built from a JDBC URL string rather than from
 * `storage.dataSourceClass`, so nothing named there is ever consulted for them.
 *
 * <h2>Why a session default does not work either</h2>
 *
 * A connection opened with `options=-c client_connection_check_interval=0`
 * reports a session value of 0 and STILL refuses the explicit `SET 5000` that
 * follows: PostgreSQL rejects the VALUE, not a departure from a default. The
 * value has to stop being sent, which is why these are the only two levers.
 *
 * <h2>WINDOWS ONLY</h2>
 *
 * On Linux the setting works and Canton enables it deliberately. Writing `0s`
 * everywhere would disable a working feature to fix a platform it cannot run
 * on. {@link #flagNeeded} is the whole of the rule.
 *
 * Author Claude/bentzn
 */
public final class ClientCheckOverlay {

    /** The key, at the end of both paths. */
    public static final String STR_KEY_INTERVAL = "client-connection-check-interval";

    /** The block both paths end in. */
    public static final String STR_KEY_BLOCK = "postgres-data-source";

    /**
     * 0 disables the check, which is the only value PostgreSQL accepts where
     * POLLRDHUP is missing. A duration rather than a bare number, because
     * Canton reads it as a `NonNegativeFiniteDuration` and refuses `0`.
     */
    public static final String STR_VALUE_OFF = "0s";


    private ClientCheckOverlay() {
    }


    /**
     * @param platform the platform the stack will run on; never null
     * @return whether this overlay has to be written at all
     */
    public static boolean flagNeeded(HostPlatform platform) {
        if (platform == null)
            throw new IllegalArgumentException("a platform is required");
        return platform.flagWindows();
    }


    /**
     * @param strParticipant the participant node the overlay applies to
     * @return the HOCON to hand to Canton with -c
     * @throws IllegalArgumentException when no participant is named
     */
    public static String render(String strParticipant) {
        if (strParticipant == null || strParticipant.isBlank())
            throw new IllegalArgumentException("a participant name is required");

        StringBuilder sb = new StringBuilder();
        sb.append("// SPDX-License-Identifier: Apache-2.0\n");
        sb.append("// Generated by raposza-canton: PostgreSQL refuses a non-zero\n");
        sb.append("// client_connection_check_interval where POLLRDHUP is missing,\n");
        sb.append("// which is every platform but Linux. The migration locks are\n");
        sb.append("// answered in the DataSource instead; see PgShim.\n");

        append(sb, "canton.participants." + strParticipant + ".ledger-api.");
        append(sb, "canton.participants." + strParticipant
                + ".parameters.ledger-api-server.indexer.");
        return sb.toString();
    }


    /**
     * @param sb what is being built
     * @param strPrefix everything up to and including the config that carries
     *        a postgres data source
     */
    private static void append(StringBuilder sb, String strPrefix) {
        sb.append(strPrefix).append(STR_KEY_BLOCK).append(".").append(STR_KEY_INTERVAL)
                .append(" = ").append(STR_VALUE_OFF).append("\n");
    }
}
