// Copyright (c) 2026 bentzn
// SPDX-License-Identifier: Apache-2.0
package com.raposza.canton.topology;

/**
 * The overlay that states in-memory storage for a 3.x sandbox EXPLICITLY.
 *
 * The `sandbox` subcommand's own `sandbox/sandbox.conf` already leaves the four
 * nodes on memory, so this overlay changes nothing about a default start. That
 * is not a reason to omit it. A stack that took its storage from a vendor
 * default would move under a Canton patch release with nothing in this project
 * saying so, which is the argument {@link SandboxPorts} already makes about the
 * six ports and for the same reason: everything load bearing is restated.
 *
 * It is the exact mirror of {@link StorageOverlay} - same four storage points,
 * same node names, same nesting - so the two can be measured against each other
 * and a difference in start-up time is a difference in STORAGE and not in the
 * shape of the file. The sequencer driver is one of the four: the reference
 * sequencer carries a database of its own under `sequencer.config`, and a
 * driver left on a default while the node moved is the half-migrated stack
 * StorageOverlay refuses to produce.
 *
 * Nothing here is persistent. A stack on this overlay writes its log and its
 * port file and no state at all, so a working directory can be deleted between
 * runs without a database left behind to time out on.
 *
 * Author Claude/bentzn
 */
public final class MemoryOverlay {

    private static final MemoryOverlay INSTANCE = new MemoryOverlay();


    private MemoryOverlay() {
        // Stateless. There is nothing to configure about memory.
    }


    /**
     * @return the single instance; a memory overlay carries no coordinates and
     *         two of them could never differ
     */
    public static MemoryOverlay of() {
        return INSTANCE;
    }


    /**
     * @return the HOCON to hand to Canton with -c
     */
    public String render() {
        StringBuilder sb = new StringBuilder();
        sb.append("// SPDX-License-Identifier: Apache-2.0\n");
        sb.append("// Generated by raposza-canton. Overlays the sandbox\n");
        sb.append("// subcommand's own configuration; only storage is restated.\n");
        sb.append("canton {\n");

        sb.append("  participants {\n");
        sb.append("    ").append(StorageOverlay.STR_NODE_PARTICIPANT).append(" {\n");
        appendMemory(sb, 6);
        sb.append("    }\n");
        sb.append("  }\n");

        sb.append("  sequencers {\n");
        sb.append("    ").append(StorageOverlay.STR_NODE_SEQUENCER).append(" {\n");
        appendMemory(sb, 6);
        sb.append("      sequencer {\n");
        sb.append("        type = \"").append(StorageOverlay.STR_SEQUENCER_TYPE).append("\"\n");
        sb.append("        config {\n");
        appendMemory(sb, 10);
        sb.append("        }\n");
        sb.append("      }\n");
        sb.append("    }\n");
        sb.append("  }\n");

        sb.append("  mediators {\n");
        sb.append("    ").append(StorageOverlay.STR_NODE_MEDIATOR).append(" {\n");
        appendMemory(sb, 6);
        sb.append("    }\n");
        sb.append("  }\n");

        sb.append("}\n");
        return sb.toString();
    }


    @Override
    public String toString() {
        return "storage overlay: memory, all four nodes";
    }


    /**
     * The same four storage points {@link StorageOverlay} writes, with the one
     * key memory takes. There is no `config` block and no connection pool:
     * `parameters.max-connections` on a memory node is a setting for a pool
     * that does not exist, and stating it would make the two overlays differ in
     * a way that has nothing to do with what is being measured.
     *
     * @param sb the buffer being rendered into
     * @param cntIndent how far in this storage block sits
     */
    private static void appendMemory(StringBuilder sb, int cntIndent) {
        String strPad = " ".repeat(cntIndent);
        sb.append(strPad).append("storage {\n");
        sb.append(strPad).append("  type = memory\n");
        sb.append(strPad).append("}\n");
    }
}
